### ISSUE TITLE
TP

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/4a-isi3-tp2-2016-2017-groupe-2-gondras-goria#1]
⚠️ C'est quoi ces variables ngValue au milieu du code ? Déjà vu le nom je vais avoir du mal à savoir ce que c'est mais en plus elles sont utilisé qu'une fois.

⚠️ Les optional rendent pas votre code extremement lisible, ça part d'une super bonne intention. Mais rappeler vous, le code doit être lisible rapidement. Un import static sur Optional peut peut-être vous aider à apporter plus de clarté.

💡 J'aimerais bien un UML avec l'intégralité des classes.

⚠️ Il faut revoir votre structure de dossier, vous avez completement cassé la structure Maven standard.

👍 L'implem c'est good sinon.

**Comment by thethego** [comment]
Je pense avoir corrigé toutes tes remarques.
Pour l'utilisation des optionnal j'ai encapsulé leurs usages dans une classe abstraite (visitorGraph) qui implémente visitor. Du coup les visiteurs héritent de visitorGraph et j'appelle des fonctions de visitorGraph plutôt que des fonctions statique de optionnal. Qu'en penses-tu ?

**Comment by Slashgear** [comment]
👍  C'est good, bonne idée la classe abstraite.

Sinon j'ai pas le temps de vérifier mais vous respectez la priorité de la multiplication sur l'addition et la soustraction ?

**Comment by thethego** [comment]
oui, j'ai modifié la classe de test pour qu'elle test aussi un graph avec des priorités et le parcour infixe renvoie "1+7*(2+3)".

**Comment by Slashgear** [comment]
Nickel
